---
# handlers file for MongoDB
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart mongod
  become: yes
  service: name=mongod state=restarted enabled=yes
